#!/bin/bash

rustc ./src/are_you_the_one_calculator.rs -o ./build/are_you_the_one_calculator && ./build/are_you_the_one_calculator
# alternative cargo build && ./target/debug/are_you_the_one_calculator
# alternative cargo run